research_task:
  description: >
    Conduct a thorough research about Tourism and Travel in {destination}.
    Find the weather report during the {date_range}
    Find the cheapest flights from {origin} to {destination}
    Find out the activites and events aligning to the {interests}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 5-10 bullet points of the most relevant information about Tourism and Travel in {destination}.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
